# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "release-deployment" ]
  pull_request:
    branches: [ "release-deployment" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          
      - uses: subosito/flutter-action@v2
        with:
          # 11
          flutter-version: "3.7.10"
          channel: 'stable'    

      - name: Get dependencies
        run: flutter pub get

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      - name: Run tests
        run: flutter test

      - name: Start release build
        run: flutter build apk

      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk

      - name: Archive files
        run: |
          sudo apt-get update
          sudo apt-get install zip
          zip -r archive.zip *


      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: "eyJpbnN0YWxsZWQiOnsiY2xpZW50X2lkIjoiMTAzMDc1MTAzMTcwMC1hZXI0bnNoOTFtb2xla2U5YmpuZWs5NnNpcHEwaDBucy5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsInByb2plY3RfaWQiOiJhcmFmYXRzdG9yZS1mNjM1MSIsImF1dGhfdXJpIjoiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLCJ0b2tlbl91cmkiOiJodHRwczovL29hdXRoMi5nb29nbGVhcGlzLmNvbS90b2tlbiIsImF1dGhfcHJvdmlkZXJfeDUwOV9jZXJ0X3VybCI6Imh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsImNsaWVudF9zZWNyZXQiOiJHT0NTUFgtX1k0Y2tESE51RUYtWVdMcDdMYjNRTDFzU0liMiIsInJlZGlyZWN0X3VyaXMiOlsiaHR0cDovL2xvY2FsaG9zdCJdfX0="
          filename: "build/app/outputs/apk/release/app-release.apk"
          folderId: "1dEQaXqjkbqDNvlA5MV0BNDVCRyek_eEs"
          name: "TestApp14-11-2023.apk" # optional string
          overwrite: "true" # optional boolean
          mimeType: "application/vnd.android.package-archive"
